// jax-tube-react/src/components/Controls.js
import React from 'react'
import { FaPlay, FaPause, FaVolumeUp, FaVolumeDown, FaStop, FaVolumeMute,  FaThumbsUp, FaThumbsDown } from 'react-icons/fa'


class Controls extends React.Component {

  play = () => {
    this.props.onPlay()
  }

  pause = () => {
    this.props.onPause()
  }

  volumeUp = () => {
    this.props.onVolumeUp()
  }

  volumeDown = () => {
    this.props.onVolumeDown()
  }

  replay = () => {
    this.props.onReplay()
  }

  toggleMute = () => {
    this.props.onToggleMute()
  }

  like = () => {
    this.props.onLike()
  }

  unlike = () => {
    this.props.onUnlike()
  }

  render() {
    const currentVideo = this.props.currentVideo
    const currentProgress = this.props.currentProgress
    return (
      <div className="controls">
        <FaPlay onClick={this.play} />
        <FaPause onClick={this.pause} />
        <FaVolumeUp onClick={this.volumeUp} />
        <FaVolumeDown onClick={this.volumeDown} />
        <FaStop onClick={this.replay} />
        <FaVolumeMute onClick={this.toggleMute} />
        <FaThumbsUp onClick={this.like}></FaThumbsUp><span>{' ' + currentVideo.likes}</span>
        <FaThumbsDown onClick={this.unlike}></FaThumbsDown><span>{' ' + currentVideo.unlikes}</span>
        <br />
        <progress value={currentProgress} max="100"></progress>
      </div>
    )
  }
}

export default Controls

// jax-tube/src/app/controls/controls.component.ts
import { Component, OnInit, Input, Output, ViewChild, EventEmitter, ElementRef } from '@angular/core';
import { Video } from '../video';

@Component({
  selector: 'app-controls',
  templateUrl: './controls.component.html',
  styleUrls: ['./controls.component.css']
})
export class ControlsComponent implements OnInit {
  @Input() currentVideo: Video;
  @Input() currentProgress: number;

  @Output() onPlay = new EventEmitter();
  @Output() onPause = new EventEmitter();
  @Output() onVolumeUp = new EventEmitter();
  @Output() onVolumeDown = new EventEmitter();
  @Output() onReplay = new EventEmitter();
  @Output() onToggleMute = new EventEmitter();
  @Output() onLike = new EventEmitter();
  @Output() onUnlike = new EventEmitter();

  @ViewChild('progressBar', { static: true }) progressBar: ElementRef;
  constructor() { }

  ngOnInit() {
    console.log(this.currentProgress, this.currentVideo)
  }

  play () { 
    console.log('onPlay emit')
    this.onPlay.emit();
  }

  pause () { 
    this.onPause.emit();
  } 

  volumeUp () {
    this.onVolumeUp.emit();
  } 

  volumeDown () {
    this.onVolumeDown.emit();
  }

  replay () { 
    this.onReplay.emit();
  } 

  toggleMute () { 
    this.onToggleMute.emit();  } 

  like () {
    this.onLike.emit();
  }

  unlike () {
    this.onUnlike.emit();
  }
}
