// jax-tube-angular/src/app/player/player.component.ts
import { Component, OnInit, Input, ViewChild, ElementRef, Output, EventEmitter } from '@angular/core';
import { Video } from '../video';

@Component({
  selector: 'app-player',
  templateUrl: './player.component.html',
  styleUrls: ['./player.component.css']
})
export class PlayerComponent implements OnInit {
  @Input() currentVideo: Video;

  @Output() onUpdateProgressBar = new EventEmitter();

  @ViewChild('player', { static: true }) player: ElementRef;

  constructor() { }

  ngOnInit() {}

  updateProgressBar () {
    this.onUpdateProgressBar.emit()
  }
}

<div>
  <video #player width="100%" height="80%" preload (timeupdate)="updateProgressBar()">
    <source *ngIf="currentVideo.url" [src]="currentVideo.url" type="video/mp4" />
    Your browser does not support the video tag.
  </video>
</div>

// jax-tube-react/src/components/Player.js
import React from 'react'

class Player extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      currentVideo: {},
      currentProgress: 0
    };
  }

  componentWillReceiveProps (nextProps) {
    console.log(nextProps)
    this.setState({
      currentVideo: nextProps.currentVideo
    })
  }

  updateProgressBar = () => {
    this.props.onUpdateProgressBar()
  }


  render() {
    return (
      <video ref={el => (this.video = el)} width="100%" height="80%" preload="auto" onTimeUpdate={this.updateProgressBar}>
        { this.state.currentVideo.url && <source src={this.state.currentVideo.url} type="video/mp4" /> }
        Your browser does not support the video tag.
      </video>
    )
  }
}

export default Player
